apiVersion: v1
kind: PersistentVolume
metadata:
  name: clique-testnet-pv-volume
  labels:
    type: local
spec:
  storageClassName: clique-testnet-nfs
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"