apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clique-testnet-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "30Gi"
  volumeName: 
  storageClassName: clique-testnet-nfs